security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)|(api/v1/doc)
            security: false
        app:
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
    providers:
        api_key_user_provider:
            id: app.security.api_key_provider
